export const CRAFT = {
  oumuamua: {
    id: 'oumuamua',
    shortName: "'Oumuamua",
    designation: '1I/2017 U1',
    hudLabel: "1I / 'OUMUAMUA",
    actLabel: 'ACT I · RECON',
    trailColor: '196,154,118',
    coreColor: '#8a6848',
    glowColor: '#c4a07a',
    nucleusLight: '#c4a07a',
  },
  atlas: {
    id: 'atlas',
    shortName: '3I/ATLAS',
    designation: '3I/ATLAS',
    hudLabel: '3I / ATLAS',
    actLabel: 'ACT II · INFILTRATION',
    trailColor: '232,210,176',
    coreColor: '#6e6054',
    glowColor: '#c8b8a0',
    nucleusLight: '#c8c0b4',
    ionColor: '155,195,245',
    dustColor: '232,210,176',
  },
};

export function getCraft(level) {
  return CRAFT[level?.craft] || CRAFT.atlas;
}

// Campaign: recon Earth as 1I/'Oumuamua, leave the system, then send 3I/ATLAS while Earth watches
export const LEVELS = [
  {
    id: 0,
    craft: 'oumuamua',
    planetIndex: 0,
    planetX: 0.32,
    earthBackdrop: 'distant',
    destLabel: 'EARTH VECTOR',
    destSub: 'BEGIN RECON',
    name: 'Interstellar Approach',
    subtitle: "1I / 'Oumuamua",
    description: "You are 'Oumuamua — a tumbling scout rock sent from the dark. Drift in from interstellar space and line up on Earth. Humanity is not watching yet. Keep it that way.",
    detectionLimit: 5,
    threatCount: 5,
    asteroidCount: 32,
    gravityWells: 1,
    bgColor: '#02010e',
    nebulaColor: 'rgba(30,10,60,0.15)',
    lore: "1I/'Oumuamua was never a comet. It was a dry, tumbling scout hull — the first visitor. Earth called it a cigar of ice. It was a silent rock.",
    threatConfig: { probe: 2, satellite: 0, hunter: 0, deepSpace: 0, relay: 0 },
    hint: "Move like a tumbling rock. 'Oumuamua has almost no coma — no sudden jets.",
  },
  {
    id: 1,
    craft: 'oumuamua',
    planetIndex: 5,
    planetX: 0.42,
    earthBackdrop: 'none',
    destLabel: 'INTEL COMPLETE',
    destSub: 'SCOPE EARTH',
    destX: 0.68,
    name: 'Scope Earth',
    subtitle: 'Read the watchers',
    description: "Earth fills the window. Slide close enough to map their satellites, cities, and scan nets — then do not linger. This is reconnaissance, not contact.",
    detectionLimit: 5,
    threatCount: 3,
    asteroidCount: 20,
    gravityWells: 2,
    bgColor: '#01040a',
    nebulaColor: 'rgba(0,30,60,0.2)',
    lore: "The scout watched the first fires, the first cities, the first satellites. It logged every dish pointed at the sky — and left before anyone could be sure it was looking back.",
    threatConfig: { probe: 1, satellite: 1, hunter: 0, deepSpace: 1, relay: 0 },
    requiredGases: ['methane'],
    hint: "Optical lock. Vent methane (Q) or their cameras confirm you are not a rock.",
  },
  {
    id: 2,
    craft: 'oumuamua',
    planetIndex: 5,
    planetX: 0.16,
    earthBackdrop: 'receding',
    destLabel: 'HELIOPAUSE',
    destSub: 'LEAVE THE SYSTEM',
    name: 'Leave the System',
    subtitle: 'Exit vector',
    description: "Recon is done. Earth shrinks behind you. Burn no extra light — just coast out past the heliopause so the scout can report and the real visitor can be sent.",
    detectionLimit: 5,
    threatCount: 4,
    asteroidCount: 18,
    gravityWells: 2,
    bgColor: '#020712',
    nebulaColor: 'rgba(20,40,90,0.18)',
    lore: "They argued for years about what 1I was. By the time the papers were published, the scout was already gone — and the next hull was already on its way.",
    threatConfig: { probe: 1, satellite: 1, hunter: 0, deepSpace: 1, relay: 0 },
    requiredGases: ['ammonia'],
    hint: "Exit dishes are radar-only. Jam them with ammonia (E) or the gate stays closed.",
  },
  {
    id: 3,
    craft: 'atlas',
    planetIndex: 0,
    planetX: 0.28,
    earthBackdrop: 'watching',
    destLabel: 'INFILTRATION GATE',
    destSub: 'STAY DARK',
    name: 'The Dispatch',
    subtitle: '3I / ATLAS',
    description: "Years later, 3I/ATLAS is sent in. Earth is in the background now — and they are watching. They remember the first visitor. Do not give them a second confirmation.",
    detectionLimit: 5,
    threatCount: 5,
    asteroidCount: 22,
    gravityWells: 2,
    bgColor: '#05020f',
    nebulaColor: 'rgba(40,10,70,0.2)',
    lore: "3I/ATLAS is the follow-up hull. Same mind, new ice. Earth built more dishes after 'Oumuamua. The disguise has to be perfect this time.",
    threatConfig: { probe: 1, satellite: 1, hunter: 0, deepSpace: 1, relay: 1 },
    requiredGases: ['methane'],
    hint: "Earth's optical net is locked. You cannot ghost this dispatch without methane (Q).",
  },
  {
    id: 4,
    craft: 'atlas',
    planetIndex: 3,
    planetX: 0.30,
    earthBackdrop: 'watching',
    destLabel: 'BLIND SIDE',
    destSub: 'USE THE GIANT',
    name: 'Jupiter Blind',
    subtitle: 'Hide in the giant',
    description: "Slingshot around Jupiter's far side. Earth's sensors cannot see through the giant — but the local satellites can. Stay a comet.",
    detectionLimit: 5,
    threatCount: 4,
    asteroidCount: 16,
    gravityWells: 2,
    bgColor: '#05020f',
    nebulaColor: 'rgba(60,20,100,0.2)',
    lore: "Atlas has posed as ice in 14 other star systems. The disguise works — until the hull moves like a ship against a planet Earth is already watching.",
    threatConfig: { probe: 1, satellite: 1, hunter: 0, deepSpace: 1, relay: 0 },
    requiredGases: ['ammonia'],
    hint: "Juno-class radar sees through ice. Ammonia (E) is the only jam that opens the blind side.",
  },
  {
    id: 5,
    craft: 'atlas',
    planetIndex: 4,
    planetX: 0.30,
    earthBackdrop: 'watching',
    destLabel: 'COLD COAST',
    destSub: 'GO DARK',
    name: 'Mars Dark',
    subtitle: 'No thrust',
    description: "A deep-space dish covers the centre lane, and Earth still sits in the background. Kill all thrust. Any power output betrays the ship under the ice.",
    detectionLimit: 5,
    threatCount: 5,
    asteroidCount: 12,
    gravityWells: 2,
    bgColor: '#0c0204',
    nebulaColor: 'rgba(80,20,20,0.2)',
    lore: "Humans found strange geometric patterns in Martian rock. They called it erosion. The scout carved them on the first pass — a waypoint for 3I.",
    threatConfig: { probe: 1, satellite: 1, hunter: 1, deepSpace: 1, relay: 0 },
    requiredGases: ['xenon'],
    hint: "Heat lock. Xenon (R) is the only mask that fools the dish — shadow will not save you.",
  },
  {
    id: 6,
    craft: 'atlas',
    planetIndex: 6,
    planetX: 0.32,
    earthBackdrop: 'watching',
    destLabel: 'THERMAL GAP',
    destSub: 'ONE SHOT',
    name: 'Inner Watch',
    subtitle: 'Venus veil',
    description: "Closer in, Earth's watch is louder. A relay and a hunter cage the lane. Xenon buys eight seconds — thread the gap while Earth stares from behind you.",
    detectionLimit: 5,
    threatCount: 6,
    asteroidCount: 10,
    gravityWells: 2,
    bgColor: '#120804',
    nebulaColor: 'rgba(180,90,20,0.18)',
    lore: "Patience is the oldest weapon. The hull once hid in a gas giant's storm for 200 years. Earth does not have that long. You do.",
    threatConfig: { probe: 1, satellite: 2, hunter: 1, deepSpace: 0, relay: 1 },
    requiredGases: ['xenon'],
    hint: "Inner Watch is a thermal cage. The gate will not open until you vent xenon (R) in the beam.",
  },
  {
    id: 7,
    craft: 'atlas',
    planetIndex: 8,
    planetX: 0.36,
    earthBackdrop: 'watching',
    destLabel: 'GHOST GATE',
    destSub: 'STAY UNDETECTED',
    name: 'Ghost the Watchers',
    subtitle: 'Triple cloak',
    description: "Earth's full net is up. Chain all three gases, use the Sun's glare, and coast through. The puzzles after this get stricter — order and timing will matter.",
    detectionLimit: 5,
    threatCount: 8,
    asteroidCount: 14,
    gravityWells: 4,
    bgColor: '#1a0800',
    nebulaColor: 'rgba(255,100,0,0.22)',
    lore: "The Sun is not the destination — it is the blind spot. They built their deepest sensors to watch the dark, not the light. Ghost them, and 3I was never here.",
    threatConfig: { probe: 2, satellite: 2, hunter: 1, deepSpace: 2, relay: 1 },
    requiredGases: ['xenon', 'ammonia', 'methane'],
    hint: "All three cloaks. Vent xenon, ammonia, then methane — the Ghost Gate stays shut until each is used.",
  },
  {
    id: 8,
    act: 3,
    craft: 'atlas',
    planetIndex: 2,
    planetX: 0.34,
    earthBackdrop: 'watching',
    destLabel: 'RING EXIT',
    destSub: 'CAMERAS THEN RADAR',
    name: 'Saturn Rings',
    subtitle: 'Order the cloaks',
    description: "Dust in the rings blinds cameras for a moment — but the dishes past the rings do not care about ice. Fool the eyes first, then jam radar. Wrong order wastes the charge.",
    detectionLimit: 5,
    threatCount: 6,
    asteroidCount: 28,
    gravityWells: 2,
    bgColor: '#0a0804',
    nebulaColor: 'rgba(180,150,70,0.16)',
    lore: "Saturn's rings are a curtain. Walk through looking like ice, then kill the radar on the far side. Reverse it and the cameras log a ship.",
    threatConfig: { probe: 2, satellite: 1, hunter: 0, deepSpace: 2, relay: 0 },
    requiredGases: ['methane', 'ammonia'],
    gasOrder: true,
    hint: "Order: methane (Q) then ammonia (E). The gate checks the sequence.",
    icon: '💍',
    accent: '#c8b97a',
    listedDiff: 'HARD',
  },
  {
    id: 9,
    act: 3,
    craft: 'atlas',
    planetIndex: 1,
    planetX: 0.30,
    earthBackdrop: 'watching',
    destLabel: 'COLD PROOF',
    destSub: 'MASK IN THE BEAM',
    name: 'Ice Moon Drift',
    subtitle: 'Vent in the dish',
    description: "A deep-space dish owns this lane. Xenon only counts if you vent it while the dish is looking at you. Cloak in empty space and the gate stays shut — they never saw the mask.",
    detectionLimit: 5,
    threatCount: 5,
    asteroidCount: 10,
    gravityWells: 2,
    bgColor: '#041018',
    nebulaColor: 'rgba(80,160,180,0.16)',
    lore: "The watchers log heat. If your mask never appears in their beam, the file says you never tried to hide — which means you were never ice.",
    threatConfig: { probe: 0, satellite: 1, hunter: 0, deepSpace: 3, relay: 1 },
    requiredGases: ['xenon'],
    cloakInScan: true,
    hint: "Drift into a heat/radar dish, then vent xenon (R) inside the scan.",
    icon: '🌙',
    accent: '#4db3c8',
    listedDiff: 'HARD',
  },
  {
    id: 10,
    act: 3,
    craft: 'atlas',
    planetIndex: 5,
    planetX: 0.26,
    earthBackdrop: 'watching',
    destLabel: 'SPLIT NET',
    destSub: 'RADAR BEFORE EYES',
    name: 'Double Bind',
    subtitle: 'Two nets, one order',
    description: "Optical and radar overlap. Jam the dishes first so the cameras lose their cue, then drop the optical cloak. Methane first lights you on radar.",
    detectionLimit: 5,
    threatCount: 6,
    asteroidCount: 12,
    gravityWells: 2,
    bgColor: '#020814',
    nebulaColor: 'rgba(40,80,140,0.18)',
    lore: "Earth's nets talk to each other. Blind the one that points the other, or both lock at once.",
    threatConfig: { probe: 1, satellite: 2, hunter: 1, deepSpace: 1, relay: 1 },
    requiredGases: ['ammonia', 'methane'],
    gasOrder: true,
    hint: "Order: ammonia (E) then methane (Q). Reverse it and the sequence resets.",
    icon: '🔗',
    accent: '#38bdf8',
    listedDiff: 'EXTREME',
  },
  {
    id: 11,
    act: 3,
    craft: 'atlas',
    planetIndex: 7,
    planetX: 0.28,
    earthBackdrop: 'watching',
    destLabel: 'INNER DARK',
    destSub: 'COLD, THEN BLIND',
    name: 'Quiet Belt',
    subtitle: 'Heat then eyes',
    description: "Mercury's baked rock throws heat. Kill your thermal signature first, then cloak from the inner cameras. Bursting here is a confession.",
    detectionLimit: 5,
    threatCount: 6,
    asteroidCount: 22,
    gravityWells: 2,
    bgColor: '#120a04',
    nebulaColor: 'rgba(160,90,30,0.16)',
    lore: "Close to the Sun, ice should scream. If you go cold first, they file you as a rock. If you go optical first, they file you as a ship that is also hot.",
    threatConfig: { probe: 2, satellite: 1, hunter: 1, deepSpace: 0, relay: 1 },
    requiredGases: ['xenon', 'methane'],
    gasOrder: true,
    hint: "Order: xenon (R) then methane (Q). Stay slow.",
    icon: '🪨',
    accent: '#8a7a6a',
    listedDiff: 'EXTREME',
  },
  {
    id: 12,
    act: 3,
    craft: 'atlas',
    planetIndex: 8,
    planetX: 0.22,
    earthBackdrop: 'watching',
    destLabel: 'NEVER HERE',
    destSub: 'THREE BEAMS, THREE MASKS',
    name: 'Never Here',
    subtitle: 'Final puzzle',
    description: "Last job. Each cloak only counts if you vent it inside a matching scan — cameras for methane, dishes for ammonia, heat for xenon — and in that order. Think, drift, then spend the charge.",
    detectionLimit: 5,
    threatCount: 7,
    asteroidCount: 12,
    gravityWells: 3,
    bgColor: '#1a0c00',
    nebulaColor: 'rgba(255,140,40,0.2)',
    lore: "If every mask appears only in the beam it was built for, the archive has three rocks and zero ships. 3I was never here.",
    threatConfig: { probe: 2, satellite: 2, hunter: 1, deepSpace: 2, relay: 1 },
    requiredGases: ['methane', 'ammonia', 'xenon'],
    gasOrder: true,
    cloakInScan: true,
    hint: "In a matching beam, in order: methane → ammonia → xenon. Empty-space vents do not count.",
    icon: '🕳',
    accent: '#ff6600',
    listedDiff: 'EXTREME',
  },
];

export function isHandoffLevel(levelId) {
  return LEVELS[levelId]?.craft === 'oumuamua' && LEVELS[levelId + 1]?.craft === 'atlas';
}

// The full solar system layout used by the Solar Run mode
// Planets ordered outer → inner (comet flies left to right or right to left depending on layout)
export const SOLAR_SYSTEM_PLANETS = [
  {
    name: 'Neptune',
    color: '#2a4fc8',
    radius: 32,
    type: 'stormy',
    ringCount: 1,
    threatDensity: 2, // how many threats cluster near this planet
  },
  {
    name: 'Uranus',
    color: '#4db3c8',
    radius: 28,
    type: 'icy',
    ringCount: 2,
    threatDensity: 2,
  },
  {
    name: 'Saturn',
    color: '#c8b97a',
    radius: 36,
    type: 'ringed',
    ringCount: 4,
    threatDensity: 3,
  },
  {
    name: 'Jupiter',
    color: '#c8a97a',
    radius: 44,
    type: 'bands',
    ringCount: 1,
    threatDensity: 3,
  },
  {
    name: 'Mars',
    color: '#c1440e',
    radius: 18,
    type: 'dusty',
    ringCount: 0,
    threatDensity: 3,
  },
  {
    name: 'Earth',
    color: '#2a7fc1',
    radius: 20,
    type: 'earth',
    ringCount: 0,
    threatDensity: 4,
  },
  {
    name: 'Venus',
    color: '#e8c97a',
    radius: 19,
    type: 'cloudy',
    ringCount: 0,
    threatDensity: 3,
  },
  {
    name: 'Mercury',
    color: '#8a7a6a',
    radius: 12,
    type: 'scorched',
    ringCount: 0,
    threatDensity: 2,
  },
  {
    name: 'Sun',
    color: '#ffcc00',
    radius: 55,
    type: 'sun',
    ringCount: 0,
    threatDensity: 0,
    isSun: true, // reaching the Sun = win condition
  },
];

export const GASES = {
  methane: {
    id: 'methane',
    name: 'Methane',
    symbol: 'CH₄',
    color: '#44ffaa',
    effect: 'visual_cloak',
    description: 'Optical cloak — blocks visual detection',
    maxDuration: 6,
    cooldown: 12,
    maxCharges: 3,
    icon: '🌿',
  },
  ammonia: {
    id: 'ammonia',
    name: 'Ammonia',
    symbol: 'NH₃',
    color: '#ffcc44',
    effect: 'radar_jam',
    description: 'Jams radar — blinds probe networks',
    maxDuration: 5,
    cooldown: 15,
    maxCharges: 3,
    icon: '📡',
  },
  xenon: {
    id: 'xenon',
    name: 'Xenon',
    symbol: 'Xe',
    color: '#cc66ff',
    effect: 'heat_mask',
    description: 'Thermal mask — hides infrared signature',
    maxDuration: 8,
    cooldown: 10,
    maxCharges: 3,
    icon: '🌡',
  },
};

export const EYES = {
  night: { id: 'night', name: 'Night Vision', color: '#00ff44', description: 'Reveals hidden threats', key: '1' },
  heat: { id: 'heat', name: 'Heat Scan', color: '#ff4400', description: 'See thermal signatures', key: '2' },
  myth: { id: 'myth', name: 'Myth Mode', color: '#aa44ff', description: 'Slow time — hold the sky', key: '3' },
};

export const SKINS = [
  { id: 'default', name: 'ICY ATLAS', desc: 'Dirty-ice nucleus, sunward coma, dust + ion tails', price: 0, unlockType: 'free', coreColor: '#6e6054', glowColor: '#c8b8a0', trailColor: '232,210,176', nucleusLight: '#c8c0b4' },
  { id: 'fire_comet', name: 'FIRE COMET', desc: 'Orange/red trail with ember particles', price: 0.99, priceId: 'price_skin_fire_comet', unlockType: 'stripe', coreColor: '#ff6622', glowColor: '#ff3300', trailColor: '255,100,20', nucleusLight: '#ff9955' },
  { id: 'dark_matter', name: 'DARK MATTER', desc: 'Black body, purple glow, distortion effect', price: 1.99, priceId: 'price_skin_dark_matter', unlockType: 'stripe', coreColor: '#110022', glowColor: '#9900ff', trailColor: '180,0,255', nucleusLight: '#440066' },
  { id: 'neon_ghost', name: 'NEON GHOST', desc: 'Transparent body, electric blue outline, ghost trail', price: 2.99, priceId: 'price_skin_neon_ghost', unlockType: 'stripe', coreColor: '#001133', glowColor: '#00aaff', trailColor: '0,200,255', nucleusLight: '#003366' },
  { id: 'golden_atlas', name: 'GOLDEN ATLAS', desc: 'Gold core, particle burst trail, glowing crown', price: 4.99, priceId: 'price_skin_golden_atlas', unlockType: 'stripe', coreColor: '#ffcc00', glowColor: '#ffaa00', trailColor: '255,200,0', nucleusLight: '#ffe066' },
  { id: 'void_reaper', name: 'VOID REAPER', desc: 'Black hole aesthetic, warping space trail, ultra rare', price: 9.99, priceId: 'price_skin_void_reaper', unlockType: 'stripe', coreColor: '#000005', glowColor: '#ff0066', trailColor: '120,0,80', nucleusLight: '#220011' },
];

export const POWERUPS = [
  { id: 'gravity_shield', name: 'GRAVITY SHIELD', gasCost: 2 },
  { id: 'probe_scrambler', name: 'PROBE SCRAMBLER', gasCost: 3 },
  { id: 'stealth_cloak', name: 'STEALTH CLOAK', gasCost: 3 },
];

export const PHYSICS = {
  BASE_SPEED: 1.2,
  MAX_SPEED: 3.8,
  MIN_SPEED: 0.18,
  BURST_SPEED: 2.8,
  GRAVITY_CONSTANT: 18000,
  DETECTION_BASE_RATE: 0.02,
  SPEED_DETECTION_MULTIPLIER: 0.8,
  PROXIMITY_DETECTION_MULTIPLIER: 0.7,
  MYTH_SLOW_FACTOR: 0.25,
  DETECTION_DECAY: 0.08,
  ALERT_SPREAD_RADIUS: 220,
};

export const DIFFICULTIES = {
  easy: { id: 'easy', label: 'EASY', color: '#34d399', borderColor: 'rgba(52,211,153,0.5)', bg: 'rgba(52,211,153,0.1)', glow: 'rgba(52,211,153,0.3)', speedMult: 0.55, threatSpeedMult: 0.45, detectionMult: 0.3, worldLengthMult: 0.9, description: 'Slow & serene. 5 gas charges. Short scan range. Perfect for new pilots.' },
  medium: { id: 'medium', label: 'MEDIUM', color: '#fbbf24', borderColor: 'rgba(251,191,36,0.5)', bg: 'rgba(251,191,36,0.1)', glow: 'rgba(251,191,36,0.3)', speedMult: 1.0, threatSpeedMult: 1.0, detectionMult: 1.0, worldLengthMult: 1.0, description: 'Balanced pace. 3 gas charges. The intended experience.' },
  hard: { id: 'hard', label: 'HARD', color: '#f87171', borderColor: 'rgba(248,113,113,0.5)', bg: 'rgba(248,113,113,0.1)', glow: 'rgba(248,113,113,0.3)', speedMult: 1.0, threatSpeedMult: 0.72, detectionMult: 1.2, worldLengthMult: 1.9, description: 'Long stealth run. Hide in planet shadow, wait for scan gaps, drift. Bursting is suicide.' },
};