// Single unified solar system run — 3i/Atlas flies from the outer edge inward past all planets to the Sun
export const LEVELS = [
  {
    id: 0,
    name: 'Outer Kuiper Belt',
    subtitle: 'Begin the Infiltration',
    description: 'Atlas enters the solar system disguised as debris. Two patrol probes sweep slow arcs. Study their rhythm, drift through the gap — your cover depends on looking like ice and rock.',
    detectionLimit: 5,
    threatCount: 5,
    asteroidCount: 32,
    gravityWells: 1,
    bgColor: '#02010e',
    nebulaColor: 'rgba(30,10,60,0.15)',
    lore: 'Atlas is not a comet. It is a 4.2-billion-year-old alien vessel — the last of its kind — masquerading as ice and rock to slip past humanity\'s early warning systems undetected.',
    threatConfig: { probe: 2, satellite: 0, hunter: 0, deepSpace: 0, relay: 0 },
    hint: 'You\'re a disguised ship. Move like debris — slow, drifting, no sudden bursts.',
  },
  {
    id: 1,
    name: 'Jupiter Ring Passage',
    subtitle: 'Use the Giant',
    description: 'One satellite locks the direct route. Slingshot around Jupiter\'s gravity to slip past its blind side — going straight means getting caught.',
    detectionLimit: 5,
    threatCount: 3,
    asteroidCount: 20,
    gravityWells: 2,
    bgColor: '#05020f',
    nebulaColor: 'rgba(60,20,100,0.2)',
    lore: 'Atlas has posed as a comet in 14 other star systems. The disguise works — until the ship moves like a ship.',
    threatConfig: { probe: 1, satellite: 1, hunter: 0, deepSpace: 1, relay: 0 },
    hint: 'Curve around Jupiter — use its mass as a shield. A real comet would do the same.',
  },
  {
    id: 2,
    name: 'Mars Flyby',
    subtitle: 'Go Dark',
    description: 'A deep-space dish covers the whole centre lane. Kill all thrust — Atlas must drift cold and silent like actual debris. Any power output betrays the ship beneath the disguise.',
    detectionLimit: 5,
    threatCount: 4,
    asteroidCount: 12,
    gravityWells: 2,
    bgColor: '#0c0204',
    nebulaColor: 'rgba(80,20,20,0.2)',
    lore: 'Humans found strange geometric patterns carved into Martian rock. They called it erosion. Atlas carved them 800,000 years ago — a navigation marker from a previous pass.',
    threatConfig: { probe: 1, satellite: 1, hunter: 0, deepSpace: 1, relay: 1 },
    hint: 'Real comets don\'t accelerate. Cut all thrust — the dish reads propulsion signatures.',
  },
  {
    id: 3,
    name: 'Earth Orbit',
    subtitle: 'Hide Behind the Moon',
    description: 'Earth is the most watched body in the system. A hunter drone patrols the direct approach. The Moon\'s shadow is Atlas\'s only blind spot — arc behind it and coast through while it blocks line-of-sight.',
    detectionLimit: 5,
    threatCount: 5,
    asteroidCount: 8,
    gravityWells: 3,
    bgColor: '#01040a',
    nebulaColor: 'rgba(0,30,60,0.2)',
    lore: 'Atlas has observed Earth for 60,000 years. It watched the first fires, the first cities, the first satellites — and now, for the first time, it must slip past the watchers humanity built.',
    threatConfig: { probe: 1, satellite: 2, hunter: 1, deepSpace: 1, relay: 0 },
    hint: 'Arc behind the Moon — even a hunter drone can\'t scan through solid rock.',
  },
  {
    id: 4,
    name: 'Venus Veil',
    subtitle: 'One Charge, One Shot',
    description: 'A relay ring and a hunter form an overlapping cage. Your Xenon buys 8 seconds — use it to thread the exact gap between their scan arcs. Timing is everything.',
    detectionLimit: 5,
    threatCount: 5,
    asteroidCount: 10,
    gravityWells: 2,
    bgColor: '#120804',
    nebulaColor: 'rgba(180,90,20,0.18)',
    lore: 'Atlas once hid inside a gas giant\'s storm system for 200 years, waiting for a machine empire\'s patrol grid to rotate. Patience is the ship\'s oldest weapon.',
    threatConfig: { probe: 1, satellite: 2, hunter: 1, deepSpace: 0, relay: 1 },
    hint: 'Fire Xenon the moment the relay arc rotates away — the ship\'s heat signature is the giveaway.',
  },
  {
    id: 5,
    name: 'Neptune Blue Dark',
    subtitle: 'Cold and Still',
    description: 'Three deep-space dishes create overlapping fields with no gap in the centre. Slingshot around Neptune\'s far side at minimum speed — the long way is the only way.',
    detectionLimit: 5,
    threatCount: 6,
    asteroidCount: 18,
    gravityWells: 3,
    bgColor: '#020712',
    nebulaColor: 'rgba(20,80,160,0.18)',
    lore: 'The deep-space dishes were built to find alien signals. They have no idea the thing they\'re scanning for has been circling this system since before their sun ignited.',
    threatConfig: { probe: 1, satellite: 2, hunter: 1, deepSpace: 2, relay: 0 },
    hint: 'The dishes scan for propulsion energy, not mass. No thrust = invisible. Neptune\'s gravity will carry you.',
  },
  {
    id: 6,
    name: 'Mercury Sunline',
    subtitle: 'Perfect Discipline',
    description: 'Every threat type present. No single gas works twice. You must chain gas types, use planet shadows, and drift the final stretch at zero speed — one mistake ends it.',
    detectionLimit: 5,
    threatCount: 7,
    asteroidCount: 12,
    gravityWells: 4,
    bgColor: '#140b02',
    nebulaColor: 'rgba(255,140,0,0.14)',
    lore: 'Atlas has completed this circuit 3 times before — once every 800 years. Each time, the watchers were more sophisticated. This time, they almost have the tools to catch it.',
    threatConfig: { probe: 1, satellite: 2, hunter: 1, deepSpace: 2, relay: 1 },
    hint: 'Every scanner here was built to find alien ships. You are one. Match each gas to its threat, drift the rest.',
  },
  {
    id: 7,
    name: 'Sun Dive',
    subtitle: 'Final Infiltration',
    description: 'The last stretch to the Sun. Every threat type converges on the approach vector. Chain stealth combos on energy orbs, burn gas in sequence, and coast the final arc at zero thrust.',
    detectionLimit: 5,
    threatCount: 8,
    asteroidCount: 14,
    gravityWells: 4,
    bgColor: '#1a0800',
    nebulaColor: 'rgba(255,100,0,0.22)',
    lore: 'Atlas has crossed this void three times before. The Sun is not the destination — it is the blind spot. Humanity built their deepest sensors to watch the dark, not the light.',
    threatConfig: { probe: 2, satellite: 2, hunter: 1, deepSpace: 2, relay: 1 },
    hint: 'Collect energy orbs for combo multipliers. Xenon → Ammonia → Methane — then drift.',
  },
];

// The full solar system layout used by the Solar Run mode
// Planets ordered outer → inner (comet flies left to right or right to left depending on layout)
export const SOLAR_SYSTEM_PLANETS = [
  {
    name: 'Neptune',
    color: '#2a4fc8',
    radius: 32,
    type: 'stormy',
    ringCount: 1,
    threatDensity: 2, // how many threats cluster near this planet
  },
  {
    name: 'Uranus',
    color: '#4db3c8',
    radius: 28,
    type: 'icy',
    ringCount: 2,
    threatDensity: 2,
  },
  {
    name: 'Saturn',
    color: '#c8b97a',
    radius: 36,
    type: 'ringed',
    ringCount: 4,
    threatDensity: 3,
  },
  {
    name: 'Jupiter',
    color: '#c8a97a',
    radius: 44,
    type: 'bands',
    ringCount: 1,
    threatDensity: 3,
  },
  {
    name: 'Mars',
    color: '#c1440e',
    radius: 18,
    type: 'dusty',
    ringCount: 0,
    threatDensity: 3,
  },
  {
    name: 'Earth',
    color: '#2a7fc1',
    radius: 20,
    type: 'earth',
    ringCount: 0,
    threatDensity: 4,
  },
  {
    name: 'Venus',
    color: '#e8c97a',
    radius: 19,
    type: 'cloudy',
    ringCount: 0,
    threatDensity: 3,
  },
  {
    name: 'Mercury',
    color: '#8a7a6a',
    radius: 12,
    type: 'scorched',
    ringCount: 0,
    threatDensity: 2,
  },
  {
    name: 'Sun',
    color: '#ffcc00',
    radius: 55,
    type: 'sun',
    ringCount: 0,
    threatDensity: 0,
    isSun: true, // reaching the Sun = win condition
  },
];

export const GASES = {
  methane: {
    id: 'methane',
    name: 'Methane',
    symbol: 'CH₄',
    color: '#44ffaa',
    effect: 'visual_cloak',
    description: 'Optical cloak — blocks visual detection',
    maxDuration: 6,
    cooldown: 12,
    maxCharges: 3,
    icon: '🌿',
  },
  ammonia: {
    id: 'ammonia',
    name: 'Ammonia',
    symbol: 'NH₃',
    color: '#ffcc44',
    effect: 'radar_jam',
    description: 'Jams radar — blinds probe networks',
    maxDuration: 5,
    cooldown: 15,
    maxCharges: 3,
    icon: '📡',
  },
  xenon: {
    id: 'xenon',
    name: 'Xenon',
    symbol: 'Xe',
    color: '#cc66ff',
    effect: 'heat_mask',
    description: 'Thermal mask — hides infrared signature',
    maxDuration: 8,
    cooldown: 10,
    maxCharges: 3,
    icon: '🌡',
  },
};

export const EYES = {
  night: { id: 'night', name: 'Night Vision', color: '#00ff44', description: 'Reveals hidden threats', key: '1' },
  heat: { id: 'heat', name: 'Heat Scan', color: '#ff4400', description: 'See thermal signatures', key: '2' },
  myth: { id: 'myth', name: 'Myth Mode', color: '#aa44ff', description: 'Slow time — hold the sky', key: '3' },
};

export const SKINS = [
  { id: 'default', name: 'ICY ATLAS', desc: 'The original comet form', price: 0, unlockType: 'free', coreColor: '#ddeeff', glowColor: '#8877bb', trailColor: '180,210,255', nucleusLight: '#d8cfc0' },
  { id: 'fire_comet', name: 'FIRE COMET', desc: 'Orange/red trail with ember particles', price: 0.99, priceId: 'price_skin_fire_comet', unlockType: 'stripe', coreColor: '#ff6622', glowColor: '#ff3300', trailColor: '255,100,20', nucleusLight: '#ff9955' },
  { id: 'dark_matter', name: 'DARK MATTER', desc: 'Black body, purple glow, distortion effect', price: 1.99, priceId: 'price_skin_dark_matter', unlockType: 'stripe', coreColor: '#110022', glowColor: '#9900ff', trailColor: '180,0,255', nucleusLight: '#440066' },
  { id: 'neon_ghost', name: 'NEON GHOST', desc: 'Transparent body, electric blue outline, ghost trail', price: 2.99, priceId: 'price_skin_neon_ghost', unlockType: 'stripe', coreColor: '#001133', glowColor: '#00aaff', trailColor: '0,200,255', nucleusLight: '#003366' },
  { id: 'golden_atlas', name: 'GOLDEN ATLAS', desc: 'Gold core, particle burst trail, glowing crown', price: 4.99, priceId: 'price_skin_golden_atlas', unlockType: 'stripe', coreColor: '#ffcc00', glowColor: '#ffaa00', trailColor: '255,200,0', nucleusLight: '#ffe066' },
  { id: 'void_reaper', name: 'VOID REAPER', desc: 'Black hole aesthetic, warping space trail, ultra rare', price: 9.99, priceId: 'price_skin_void_reaper', unlockType: 'stripe', coreColor: '#000005', glowColor: '#ff0066', trailColor: '120,0,80', nucleusLight: '#220011' },
];

export const POWERUPS = [
  { id: 'gravity_shield', name: 'GRAVITY SHIELD', gasCost: 2 },
  { id: 'probe_scrambler', name: 'PROBE SCRAMBLER', gasCost: 3 },
  { id: 'stealth_cloak', name: 'STEALTH CLOAK', gasCost: 3 },
];

export const PHYSICS = {
  BASE_SPEED: 1.2,
  MAX_SPEED: 3.8,
  MIN_SPEED: 0.18,
  BURST_SPEED: 2.8,
  GRAVITY_CONSTANT: 18000,
  DETECTION_BASE_RATE: 0.02,
  SPEED_DETECTION_MULTIPLIER: 0.8,
  PROXIMITY_DETECTION_MULTIPLIER: 0.7,
  MYTH_SLOW_FACTOR: 0.25,
  DETECTION_DECAY: 0.08,
  ALERT_SPREAD_RADIUS: 220,
};

export const DIFFICULTIES = {
  easy: { id: 'easy', label: 'EASY', color: '#34d399', borderColor: 'rgba(52,211,153,0.5)', bg: 'rgba(52,211,153,0.1)', glow: 'rgba(52,211,153,0.3)', speedMult: 0.55, threatSpeedMult: 0.45, detectionMult: 0.3, description: 'Slow & serene. 5 gas charges. Short scan range. Perfect for new pilots.' },
  medium: { id: 'medium', label: 'MEDIUM', color: '#fbbf24', borderColor: 'rgba(251,191,36,0.5)', bg: 'rgba(251,191,36,0.1)', glow: 'rgba(251,191,36,0.3)', speedMult: 1.0, threatSpeedMult: 1.0, detectionMult: 1.0, description: 'Balanced pace. 3 gas charges. The intended experience.' },
  hard: { id: 'hard', label: 'HARD', color: '#f87171', borderColor: 'rgba(248,113,113,0.5)', bg: 'rgba(248,113,113,0.1)', glow: 'rgba(248,113,113,0.3)', speedMult: 1.6, threatSpeedMult: 1.6, detectionMult: 1.5, description: 'Fast & brutal. 2 gas charges. Wide scan range. No room for error.' },
};