export const STRIPE_PRODUCTS = [
  {
    id: 'price_1TFOBNBLkDedke6Gi5v3wOvT',
    name: "OUMUAMUA GHOST",
    description: "Premium stealth skin",
    type: 'skin',
    badge: 'Skin',
  },
  {
    id: 'price_1TFOBOBLkDedke6GqHjnryP7',
    name: "HALLEY'S ECHO",
    description: "Premium comet skin",
    type: 'skin',
    badge: 'Skin',
  },
  {
    id: 'price_1TFOBOBLkDedke6GIUjqNx1G',
    name: 'DARK MATTER CLOAK',
    description: 'Premium dark skin',
    type: 'skin',
    badge: 'Skin',
  },
  {
    id: 'price_1TFOBPBLkDedke6GHA8rk4l4',
    name: 'SOLAR PHANTOM',
    description: 'Premium radiant skin',
    type: 'skin',
    badge: 'Skin',
  },
  {
    id: 'price_1TFOBQBLkDedke6GpiB81YRc',
    name: 'FIRE TRAIL',
    description: 'Unlock a blazing trail effect',
    type: 'trail',
    badge: 'Trail',
  },
  {
    id: 'price_1TFOBRBLkDedke6GHJo3MQTs',
    name: 'ICE CRYSTAL TRAIL',
    description: 'Unlock a frozen trail effect',
    type: 'trail',
    badge: 'Trail',
  },
  {
    id: 'price_1TFOBRBLkDedke6G0qsbsX35',
    name: 'PLASMA TRAIL',
    description: 'Unlock a charged plasma trail',
    type: 'trail',
    badge: 'Trail',
  },
  {
    id: 'price_1TFOBSBLkDedke6Ghsj9MmUd',
    name: 'STEALTH CLOAK x10',
    description: 'Add 10 stealth cloak charges',
    type: 'powerup',
    badge: 'Powerup',
  },
  {
    id: 'price_1TFOBTBLkDedke6GbCLUk0UB',
    name: 'PROBE SCRAMBLER x10',
    description: 'Add 10 probe scrambler charges',
    type: 'powerup',
    badge: 'Powerup',
  },
  {
    id: 'price_1TFOBUBLkDedke6GxxLO5EsR',
    name: 'POWER BUNDLE',
    description: '5 of each powerup in one pack',
    type: 'bundle',
    badge: 'Bundle',
  },
  {
    id: 'price_1TFOBUBLkDedke6GqsJSX6YS',
    name: 'MISSION PACK',
    description: 'Unlock extra mission levels',
    type: 'mission_pack',
    badge: 'Mission Pack',
  },
];